CREATE TABLE consumption (
    CONSUMPTION_ID varchar(255) NOT NULL,
    YEAR_FIELD DATE NOT NULL,
    CONSUMPTION FLOAT,
    PRIMARY KEY (CONSUMPTION_ID)
);


CREATE TABLE inflation (
    INFLATION_ID varchar(255) NOT NULL,
    YEAR_FIELD DATE NOT NULL,
    INFLATION FLOAT,
    PRIMARY KEY (INFLATION_ID)
);

CREATE TABLE gdp (
    GDP_ID varchar(255) NOT NULL,
    YEAR_FIELD DATE NOT NULL,
    GDP varchar(255),
    PRIMARY KEY (GDP_ID)
);

ALTER TABLE gdp
ALTER COLUMN GDP bigint; 

CREATE TABLE unemployment (
    UNEMP_ID varchar(255) NOT NULL,
    YEAR_FIELD DATE NOT NULL,
    Unemployment FLOAT,
	Employment FLOAT,
    PRIMARY KEY (UNEMP_ID)
);


CREATE TABLE nepal_fact_table (
	FACT_ID varchar(255) NOT NULL,
	CONSUMPTION_ID varchar(255) NOT NULL,
	GDP_ID varchar(255) NOT NULL,
	INFLATION_ID varchar(255) NOT NULL,
	UNEMP_ID varchar(255) NOT NULL,
	CONSUMPTION FLOAT,
	INFLATION FLOAT,
	Unemployment FLOAT,
	Employment FLOAT,
	GDP varchar(255),
    YEAR_FIELD DATE NOT NULL,
    PRIMARY KEY (FACT_ID),
	FOREIGN KEY (CONSUMPTION_ID) REFERENCES consumption(CONSUMPTION_ID),
	FOREIGN KEY (GDP_ID) REFERENCES gdp(GDP_ID),
	FOREIGN KEY (INFLATION_ID) REFERENCES inflation(INFLATION_ID),
	FOREIGN KEY (UNEMP_ID) REFERENCES unemployment(UNEMP_ID)
);

